
spring:
  application:
    name: busManagement

  data:
      mongodb:
        uri: mongodb://localhost:27017/busManagementdb
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${MAIL_USERNAME}